// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tap.hw.domain;

import tap.hw.domain.Sport;

privileged aspect Sport_Roo_JavaBean {
    
    public String Sport.getName() {
        return this.name;
    }
    
    public void Sport.setName(String name) {
        this.name = name;
    }
    
}
