// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tap.hw.domain;

import org.springframework.beans.factory.annotation.Configurable;
import tap.hw.domain.SchoolIntegrationTest;

privileged aspect SchoolIntegrationTest_Roo_Configurable {
    
    declare @type: SchoolIntegrationTest: @Configurable;
    
}
