// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tap.hw.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import tap.hw.domain.SportLevel;
import tap.hw.domain.SportLevelDataOnDemand;

privileged aspect SportLevelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SportLevelDataOnDemand: @Component;
    
    private Random SportLevelDataOnDemand.rnd = new SecureRandom();
    
    private List<SportLevel> SportLevelDataOnDemand.data;
    
    public SportLevel SportLevelDataOnDemand.getNewTransientSportLevel(int index) {
        SportLevel obj = new SportLevel();
        setCode(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void SportLevelDataOnDemand.setCode(SportLevel obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void SportLevelDataOnDemand.setName(SportLevel obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public SportLevel SportLevelDataOnDemand.getSpecificSportLevel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SportLevel obj = data.get(index);
        Long id = obj.getId();
        return SportLevel.findSportLevel(id);
    }
    
    public SportLevel SportLevelDataOnDemand.getRandomSportLevel() {
        init();
        SportLevel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SportLevel.findSportLevel(id);
    }
    
    public boolean SportLevelDataOnDemand.modifySportLevel(SportLevel obj) {
        return false;
    }
    
    public void SportLevelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SportLevel.findSportLevelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SportLevel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SportLevel>();
        for (int i = 0; i < 10; i++) {
            SportLevel obj = getNewTransientSportLevel(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
