// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tap.hw.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import tap.hw.domain.Sport;
import tap.hw.domain.SportDataOnDemand;
import tap.hw.domain.SportIntegrationTest;

privileged aspect SportIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SportIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SportIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SportIntegrationTest: @Transactional;
    
    @Autowired
    private SportDataOnDemand SportIntegrationTest.dod;
    
    @Test
    public void SportIntegrationTest.testCountSports() {
        Assert.assertNotNull("Data on demand for 'Sport' failed to initialize correctly", dod.getRandomSport());
        long count = Sport.countSports();
        Assert.assertTrue("Counter for 'Sport' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SportIntegrationTest.testFindSport() {
        Sport obj = dod.getRandomSport();
        Assert.assertNotNull("Data on demand for 'Sport' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sport' failed to provide an identifier", id);
        obj = Sport.findSport(id);
        Assert.assertNotNull("Find method for 'Sport' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Sport' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SportIntegrationTest.testFindAllSports() {
        Assert.assertNotNull("Data on demand for 'Sport' failed to initialize correctly", dod.getRandomSport());
        long count = Sport.countSports();
        Assert.assertTrue("Too expensive to perform a find all test for 'Sport', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Sport> result = Sport.findAllSports();
        Assert.assertNotNull("Find all method for 'Sport' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Sport' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SportIntegrationTest.testFindSportEntries() {
        Assert.assertNotNull("Data on demand for 'Sport' failed to initialize correctly", dod.getRandomSport());
        long count = Sport.countSports();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Sport> result = Sport.findSportEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Sport' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Sport' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SportIntegrationTest.testFlush() {
        Sport obj = dod.getRandomSport();
        Assert.assertNotNull("Data on demand for 'Sport' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sport' failed to provide an identifier", id);
        obj = Sport.findSport(id);
        Assert.assertNotNull("Find method for 'Sport' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySport(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Sport' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SportIntegrationTest.testMergeUpdate() {
        Sport obj = dod.getRandomSport();
        Assert.assertNotNull("Data on demand for 'Sport' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sport' failed to provide an identifier", id);
        obj = Sport.findSport(id);
        boolean modified =  dod.modifySport(obj);
        Integer currentVersion = obj.getVersion();
        Sport merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Sport' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SportIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Sport' failed to initialize correctly", dod.getRandomSport());
        Sport obj = dod.getNewTransientSport(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Sport' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Sport' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Sport' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SportIntegrationTest.testRemove() {
        Sport obj = dod.getRandomSport();
        Assert.assertNotNull("Data on demand for 'Sport' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sport' failed to provide an identifier", id);
        obj = Sport.findSport(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Sport' with identifier '" + id + "'", Sport.findSport(id));
    }
    
}
